# Generated by Django 5.2.1 on 2025-06-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_result_grade_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('computer_science', 'Computer Science'), ('information_technology', 'Information Technology'), ('electronics', 'Electronics & Communication'), ('mechanical', 'Mechanical Engineering'), ('civil', 'Civil Engineering'), ('electrical', 'Electrical Engineering'), ('business', 'Business Administration'), ('arts', 'Arts & Humanities'), ('science', 'Science'), ('commerce', 'Commerce'), ('other', 'Other')], default='computer_science', max_length=50),
        ),
    ]
